dist: trusty
language: c++
sudo: false

script:
  - export CXX=$USE_CXX
  - export CC=$USE_CC
  - autoreconf -f
  - mkdir -p build-toolchain/install
  - pushd build-toolchain
  - ../toolchain/build-crossgcc.sh -o "$PWD"/build -p "$PWD"/install -q
  - popd
  - mkdir -p build-$CXX
  - printf "cd build-%s\n" "$CXX"
  - cd build-$CXX
  - export PATH="$PWD"/../build-toolchain/install/bin:"$PATH"
  - ../bootstrap
  - make

branches:
  only:
    - master

env:
  matrix:
    - USE_CC=gcc-5 USE_CXX=g++-5

addons:
  apt:
    sources:
        - ubuntu-toolchain-r-test
    packages:
        - gcc-5
        - g++-5
        - gcc-5-multilib
        - g++-5-multilib
        - clang
        - automake
        - autoconf
        - qemu

notifications:
    email:
        - doug16k@gmail.com

after_success:
    - cd build-$CXX && ls
