name: dgos CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:    

    runs-on: ubuntu-latest

    steps:
    - name: banner
      run: printf "Building with %d processors\n" "$(nproc)"
      shell: bash
    - name: build cpu
      run: "grep -oP '(?<=model name\t: ).*' /proc/cpuinfo|head -n1"
      shell: bash
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v2.1.1
      id: cache
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ./cibuild/toolchain_install
        # An explicit key for restoring and saving the cache
        key: toolchain
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        #restore-keys: # optional
    - name: dependencies
      run: sudo apt-get update && sudo apt-get install lemon mtools genisoimage qemu-system-x86 cpu-checker
    - name: kvm test
      run: kvm-ok
      shell: bash
    - name: toolchain
      run: mkdir -p cibuild && cd cibuild && ../toolchain/build-crossgcc.sh -q -o toolchain_build -p toolchain_install
      if: steps.cache.outputs.cache-hit != 'true'
    - name: bootstrap
      run: export PATH="$PWD/cibuild/toolchain_install/bin:$PATH" && cd cibuild && ../bootstrap
    - name: disks
      run: export PATH="$PWD/cibuild/toolchain_install/bin:$PATH" && cd cibuild && make disks -j$(nproc)
