name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: toolchain
      run: bash -c 'mkdir -p cibuild && cd cibuild && ../toolchain/build-crossgcc.sh -o toolchain_build -p toolchain_install'
    - name: bootstrap
      run: bash -c 'export PATH="$PWD/cibuild/toolchain_install/bin:$PATH" && cd cibuild && ../bootstrap'
    - name: disks
      run: bash -c 'cd cibuild && make disks'
    - name: Cache
      uses: actions/cache@v2.1.1
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: cibuild/toolchain/toolchain_install
        # An explicit key for restoring and saving the cache
        key: toolchain
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        #restore-keys: # optional
